import { MigrationInterface, QueryRunner } from "typeorm";

export class AddCarpetaDriveUrlToPersona1785352431818 implements MigrationInterface {
    name = 'AddCarpetaDriveUrlToPersona1785352431818'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "evidencias" DROP CONSTRAINT "evidencias_id_actividad_fkey"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "usuarios_id_rol_fkey"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "usuarios_id_area_fkey"`);
        await queryRunner.query(`ALTER TABLE "obligaciones" DROP CONSTRAINT "obligaciones_id_contrato_fkey"`);
        await queryRunner.query(`ALTER TABLE "contratos" DROP CONSTRAINT "contratos_id_usuario_fkey"`);
        await queryRunner.query(`ALTER TABLE "informe_gf" DROP CONSTRAINT "informe_gf_id_informe_fkey"`);
        await queryRunner.query(`ALTER TABLE "versiones" DROP CONSTRAINT "versiones_id_informe_fkey"`);
        await queryRunner.query(`ALTER TABLE "informes" DROP CONSTRAINT "informes_id_usuario_fkey"`);
        await queryRunner.query(`ALTER TABLE "informes" DROP CONSTRAINT "informes_id_periodo_fkey"`);
        await queryRunner.query(`ALTER TABLE "informe_gc" DROP CONSTRAINT "informe_gc_id_informe_fkey"`);
        await queryRunner.query(`ALTER TABLE "informe_gc" DROP CONSTRAINT "informe_gc_id_contrato_fkey"`);
        await queryRunner.query(`ALTER TABLE "actividades" DROP CONSTRAINT "actividades_id_informe_gc_fkey"`);
        await queryRunner.query(`ALTER TABLE "novedades" DROP CONSTRAINT "novedades_fk_version_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_evidencias_actividad"`);
        await queryRunner.query(`DROP INDEX "public"."idx_usuarios_rol"`);
        await queryRunner.query(`DROP INDEX "public"."idx_usuarios_area"`);
        await queryRunner.query(`DROP INDEX "public"."idx_obligaciones_contrato"`);
        await queryRunner.query(`DROP INDEX "public"."idx_contratos_usuario"`);
        await queryRunner.query(`DROP INDEX "public"."idx_informes_usuario"`);
        await queryRunner.query(`DROP INDEX "public"."idx_informes_periodo"`);
        await queryRunner.query(`DROP INDEX "public"."idx_informe_gc_contrato"`);
        await queryRunner.query(`DROP INDEX "public"."idx_actividades_informe_gc"`);
        await queryRunner.query(`DROP INDEX "public"."idx_novedades_version"`);
        await queryRunner.query(`CREATE TABLE "notificaciones" ("id_notificacion" SERIAL NOT NULL, "tipo" character varying(20) NOT NULL DEFAULT 'info', "mensaje" text NOT NULL, "leida" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "id_usuario" integer NOT NULL, CONSTRAINT "PK_ff498b8eb6b226a9fc52889ddac" PRIMARY KEY ("id_notificacion"))`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD "carpeta_drive_url" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "evidencias" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "evidencias" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "areas" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "areas" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "usuarios" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "usuarios" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "obligaciones" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "obligaciones" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "contratos" DROP COLUMN "estado"`);
        await queryRunner.query(`ALTER TABLE "contratos" ADD "estado" character varying(30) NOT NULL DEFAULT 'activo'`);
        await queryRunner.query(`ALTER TABLE "contratos" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "contratos" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "informe_gf" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "informe_gf" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "periodos_carga" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "periodos_carga" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "versiones" ALTER COLUMN "fecha_version" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "informes" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "informes" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "informe_gc" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "informe_gc" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "actividades" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "actividades" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "evidencias" ADD CONSTRAINT "FK_41a0d8d68cd3e8630ab0a2badab" FOREIGN KEY ("id_actividad") REFERENCES "actividades"("id_actividad") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "FK_98bf89ebf4b0be2d3825f54e56c" FOREIGN KEY ("id_rol") REFERENCES "roles"("id_rol") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "FK_ce9ce4560bed499dd55a3319349" FOREIGN KEY ("id_area") REFERENCES "areas"("id_area") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "obligaciones" ADD CONSTRAINT "FK_c128158b1610b6ca0d8e65e96aa" FOREIGN KEY ("id_contrato") REFERENCES "contratos"("id_contrato") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contratos" ADD CONSTRAINT "FK_a44068368e6e16b9ce99c5e3db0" FOREIGN KEY ("id_usuario") REFERENCES "usuarios"("id_usuario") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "informe_gf" ADD CONSTRAINT "FK_ae945c694ff856b2c9b9a27a734" FOREIGN KEY ("id_informe") REFERENCES "informes"("id_informe") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "versiones" ADD CONSTRAINT "FK_28981b7748b28b6ffce83359ed3" FOREIGN KEY ("id_informe") REFERENCES "informes"("id_informe") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "informes" ADD CONSTRAINT "FK_d20add2e68bb44b090355cbace4" FOREIGN KEY ("id_usuario") REFERENCES "usuarios"("id_usuario") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "informes" ADD CONSTRAINT "FK_aece6c3a6beeed1cd3652b3291a" FOREIGN KEY ("id_periodo") REFERENCES "periodos_carga"("id_periodo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "informe_gc" ADD CONSTRAINT "FK_130df1d67eb5c20eb42ea7332f9" FOREIGN KEY ("id_informe") REFERENCES "informes"("id_informe") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "informe_gc" ADD CONSTRAINT "FK_1f06a198c2e9da0d34b35e1fbdb" FOREIGN KEY ("id_contrato") REFERENCES "contratos"("id_contrato") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actividades" ADD CONSTRAINT "FK_e6fdf870515b2dbcab99efd5dde" FOREIGN KEY ("id_informe_gc") REFERENCES "informe_gc"("id_informe_gc") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notificaciones" ADD CONSTRAINT "FK_ff51040b8609869dff4e7cf2bcd" FOREIGN KEY ("id_usuario") REFERENCES "usuarios"("id_usuario") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "novedades" ADD CONSTRAINT "FK_7030acf1aa2a7745971260b3d35" FOREIGN KEY ("fk_version") REFERENCES "versiones"("id_version") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "novedades" DROP CONSTRAINT "FK_7030acf1aa2a7745971260b3d35"`);
        await queryRunner.query(`ALTER TABLE "notificaciones" DROP CONSTRAINT "FK_ff51040b8609869dff4e7cf2bcd"`);
        await queryRunner.query(`ALTER TABLE "actividades" DROP CONSTRAINT "FK_e6fdf870515b2dbcab99efd5dde"`);
        await queryRunner.query(`ALTER TABLE "informe_gc" DROP CONSTRAINT "FK_1f06a198c2e9da0d34b35e1fbdb"`);
        await queryRunner.query(`ALTER TABLE "informe_gc" DROP CONSTRAINT "FK_130df1d67eb5c20eb42ea7332f9"`);
        await queryRunner.query(`ALTER TABLE "informes" DROP CONSTRAINT "FK_aece6c3a6beeed1cd3652b3291a"`);
        await queryRunner.query(`ALTER TABLE "informes" DROP CONSTRAINT "FK_d20add2e68bb44b090355cbace4"`);
        await queryRunner.query(`ALTER TABLE "versiones" DROP CONSTRAINT "FK_28981b7748b28b6ffce83359ed3"`);
        await queryRunner.query(`ALTER TABLE "informe_gf" DROP CONSTRAINT "FK_ae945c694ff856b2c9b9a27a734"`);
        await queryRunner.query(`ALTER TABLE "contratos" DROP CONSTRAINT "FK_a44068368e6e16b9ce99c5e3db0"`);
        await queryRunner.query(`ALTER TABLE "obligaciones" DROP CONSTRAINT "FK_c128158b1610b6ca0d8e65e96aa"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "FK_ce9ce4560bed499dd55a3319349"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "FK_98bf89ebf4b0be2d3825f54e56c"`);
        await queryRunner.query(`ALTER TABLE "evidencias" DROP CONSTRAINT "FK_41a0d8d68cd3e8630ab0a2badab"`);
        await queryRunner.query(`ALTER TABLE "actividades" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "actividades" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "informe_gc" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "informe_gc" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "informes" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "informes" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "versiones" ALTER COLUMN "fecha_version" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "periodos_carga" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "periodos_carga" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "informe_gf" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "informe_gf" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "contratos" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "contratos" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "contratos" DROP COLUMN "estado"`);
        await queryRunner.query(`ALTER TABLE "contratos" ADD "estado" character varying(50) NOT NULL DEFAULT 'activo'`);
        await queryRunner.query(`ALTER TABLE "obligaciones" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "obligaciones" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "usuarios" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "usuarios" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "areas" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "areas" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "evidencias" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "evidencias" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP COLUMN "carpeta_drive_url"`);
        await queryRunner.query(`DROP TABLE "notificaciones"`);
        await queryRunner.query(`CREATE INDEX "idx_novedades_version" ON "novedades" USING btree ("fk_version") `);
        await queryRunner.query(`CREATE INDEX "idx_actividades_informe_gc" ON "actividades" USING btree ("id_informe_gc") `);
        await queryRunner.query(`CREATE INDEX "idx_informe_gc_contrato" ON "informe_gc" USING btree ("id_contrato") `);
        await queryRunner.query(`CREATE INDEX "idx_informes_periodo" ON "informes" USING btree ("id_periodo") `);
        await queryRunner.query(`CREATE INDEX "idx_informes_usuario" ON "informes" USING btree ("id_usuario") `);
        await queryRunner.query(`CREATE INDEX "idx_contratos_usuario" ON "contratos" USING btree ("id_usuario") `);
        await queryRunner.query(`CREATE INDEX "idx_obligaciones_contrato" ON "obligaciones" USING btree ("id_contrato") `);
        await queryRunner.query(`CREATE INDEX "idx_usuarios_area" ON "usuarios" USING btree ("id_area") `);
        await queryRunner.query(`CREATE INDEX "idx_usuarios_rol" ON "usuarios" USING btree ("id_rol") `);
        await queryRunner.query(`CREATE INDEX "idx_evidencias_actividad" ON "evidencias" USING btree ("id_actividad") `);
        await queryRunner.query(`ALTER TABLE "novedades" ADD CONSTRAINT "novedades_fk_version_fkey" FOREIGN KEY ("fk_version") REFERENCES "versiones"("id_version") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actividades" ADD CONSTRAINT "actividades_id_informe_gc_fkey" FOREIGN KEY ("id_informe_gc") REFERENCES "informe_gc"("id_informe_gc") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "informe_gc" ADD CONSTRAINT "informe_gc_id_contrato_fkey" FOREIGN KEY ("id_contrato") REFERENCES "contratos"("id_contrato") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "informe_gc" ADD CONSTRAINT "informe_gc_id_informe_fkey" FOREIGN KEY ("id_informe") REFERENCES "informes"("id_informe") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "informes" ADD CONSTRAINT "informes_id_periodo_fkey" FOREIGN KEY ("id_periodo") REFERENCES "periodos_carga"("id_periodo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "informes" ADD CONSTRAINT "informes_id_usuario_fkey" FOREIGN KEY ("id_usuario") REFERENCES "usuarios"("id_usuario") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "versiones" ADD CONSTRAINT "versiones_id_informe_fkey" FOREIGN KEY ("id_informe") REFERENCES "informes"("id_informe") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "informe_gf" ADD CONSTRAINT "informe_gf_id_informe_fkey" FOREIGN KEY ("id_informe") REFERENCES "informes"("id_informe") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contratos" ADD CONSTRAINT "contratos_id_usuario_fkey" FOREIGN KEY ("id_usuario") REFERENCES "usuarios"("id_usuario") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "obligaciones" ADD CONSTRAINT "obligaciones_id_contrato_fkey" FOREIGN KEY ("id_contrato") REFERENCES "contratos"("id_contrato") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "usuarios_id_area_fkey" FOREIGN KEY ("id_area") REFERENCES "areas"("id_area") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "usuarios_id_rol_fkey" FOREIGN KEY ("id_rol") REFERENCES "roles"("id_rol") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evidencias" ADD CONSTRAINT "evidencias_id_actividad_fkey" FOREIGN KEY ("id_actividad") REFERENCES "actividades"("id_actividad") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
